# Generated by Django 5.1.4 on 2025-01-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Never',
        ),
    ]
